version: '3.4'

services:
  proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/traefik.yml"
  
  nginx:
    image: nginx:alpine
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.mario21ic.com`) && Path(`/traefik/`) && Query(`foo=bar`)"
    volumes:
      - ./index.html:/usr/share/nginx/html/traefik/index.html

  apache:
    image: httpd:alpine
    labels:
      - "traefik.http.routers.apache.rule=Host(`apache.mario21ic.com`) || Host(`web.mario21ic.com`)"

  app:
    image: app:latest
    # container_name: app
    build: 
      context: ./docker/
      # dockerfile: ./docker/Dockerfile
    labels:
      - "traefik.http.routers.app.rule=Host(`app.mario21ic.com`)"
      - "traefik.http.services.app.loadbalancer.server.port=8081"
