version: '3.4'

services:
  proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.http.routers.myauth.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.middlewares.my-auth.basicauth.users=admin:$$2y$$05$$U.U0XSwpOnYq35mGy9Rnru1lS60T.o1OsTbuslWcv/zefwroyFEhe"
      - "traefik.http.routers.myauth.middlewares=my-auth"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
  
  nginx:
    image: nginx:alpine
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.mario21ic.com`) && Path(`/traefik/`) && Query(`foo=bar`)"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/traefik,/foobar"
      - "traefik.http.routers.nginx.middlewares=test-stripprefix"

  apache:
    image: httpd:alpine
    labels:
      - "traefik.http.routers.apache.rule=Host(`apache.mario21ic.com`) || Host(`web.mario21ic.com`)"

