version: '3.4'

services:
  proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
  
  nginx:
    image: nginx:alpine
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.mario21ic.com`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  apache:
    image: httpd:alpine
    labels:
      - "traefik.http.routers.apache.rule=Host(`apache.mario21ic.com`) || Host(`web.mario21ic.com`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls.certresolver=myresolver"

