entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
    myresolver:
        acme:
            email: mario21ic@gmail.com
            storage: /acme.json
            httpChallenge:
                entryPoint: web

api:
    dashboard: true
    insecure: true
