providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        #exposedByDefault: false
        #constraints: "Label(`environment`, `dev`)"
    file:
        filename: /config.yml
api:
    dashboard: true
    insecure: true

log:
    filePath: "/traefik.log"
    level: DEBUG
    format: json

